baseURL = "https://pointlander.github.io"
languageCode = "en-us"
title = "Pointlander"
theme = "ananke"

[params]
  github = "https://github.com/pointlander"
  linkedin = "https://www.linkedin.com/in/andrew-snodgrass-62916793"
  featured_image = "/images/night.jpg"
